version: "3.7"

services:
  db:
    image: mongo
    container_name: progotan-mongo
    env_file: ./Api/.env.development
    restart: always
    ports:
      - 27017:27017
    volumes:
      - ./Api/db/mongo-init.sh:/docker-entrypoint-initdb.d/mongo-init.sh
      - ./Api/db/data:/data/db
      - ./Api/db/seed:/seed

  api:
    image: node:16-alpine
    container_name: progotan-api
    env_file: ./Api/.env
    depends_on:
      - db
    ports:
      - "5000:3000"
      - "587:587"
    volumes:
      - ./Api:/data
    working_dir: /data
    command: ./node_modules/.bin/nodemon

  CP:
    image: node:16-alpine
    container_name: progotan-cp
    env_file: ./CP/.env
    ports:
      - "3000:3000"
    volumes:
      - ./CP:/data
    working_dir: /data
    command: npm start
    stdin_open: true
