version: "3.7"

services:
  Api:
    image: node:16-alpine
    container_name: ecotrip-api
    env_file: ./Api/.env
    depends_on:
      - db
    ports:
      - "5000:3000"
      - "587:587"
    volumes:
      - ./Api:/data
    working_dir: /data
    command: ./node_modules/.bin/nodemon

  CP:
    image: node:16-alpine
    container_name: ecotrip-cp
    env_file: ./CP/.env
    ports:
      - "3000:3000"
    volumes:
      - ./CP:/data
    working_dir: /data
    command: npm start
    stdin_open: true

  App:
    image: node:16-alpine
    container_name: ecotrip-app
    env_file: ./App/.env
    ports:
      - "80:3000"
    volumes:
      - ./App:/data
    working_dir: /data
    command: npm start
    stdin_open: true
