AWSTemplateFormatVersion: "2010-09-09"
Transform: AWS::Serverless-2016-10-31

Parameters:
  URI:
    Type: String
    Description: The URI used to name resources [projectName-env-gitUsername]
  Url:
    Type: String
    Description: The enpoint to cognito auth
  SesArn:
    Type: String
    Description: The ARN of Simple email service (SES)
  AcmArn:
    Type: String
    Description: The ARN of the ssl certificate genereted on ACM
    Default: ""

Conditions:
  CustomDomain: !Not [!Equals [!Ref AcmArn, ""]]

Resources:
  UserPool:
    Type: AWS::Cognito::UserPool
    DeletionPolicy: Delete
    UpdateReplacePolicy: Retain
    Properties:
      UserPoolName: !Sub ${URI}-user-pool
      AutoVerifiedAttributes:
        - email
      EmailConfiguration:
        EmailSendingAccount: DEVELOPER
        From: !Sub ${URI}@ecotrip.meblabs.dev
        SourceArn: !Ref SesArn
      Schema:
        - Name: email
          AttributeDataType: String
          Mutable: false
          Required: true
        - Name: name
          AttributeDataType: String
          Mutable: true
          Required: true
        - Name: family_name
          AttributeDataType: String
          Mutable: true
          Required: true
        - Name: phone
          AttributeDataType: String
          Mutable: true
          Required: false
        - Name: locale
          AttributeDataType: String
          Mutable: true
          Required: false
        - Name: updated_at
          AttributeDataType: Number
          Mutable: true
          Required: false

  UserPoolClient:
    Type: AWS::Cognito::UserPoolClient
    DeletionPolicy: Delete
    UpdateReplacePolicy: Retain
    Properties:
      ClientName: !Sub ${URI}-user-client
      UserPoolId: !Ref UserPool

  UserPoolDomain:
    Type: AWS::Cognito::UserPoolDomain
    Properties:
      Domain: !Ref Url
      UserPoolId: !Ref UserPool
      CustomDomainConfig: !If
        - CustomDomain
        - CertificateArn: !Ref AcmArn
        - !Ref AWS::NoValue

Outputs:
  CognitoUserPoolID:
    Value: !Ref UserPool
    Description: The UserPool ID
  CognitoAppClientID:
    Value: !Ref UserPoolClient
    Description: The app client
