#!/bin/bash

# LOAD EXTERNAL VARIABLES FOR LOCAL EXEC
source ../.env

while getopts ":hSe:p:l:t:a:g:d:s:" opt; do
	case $opt in
	h)
		echo "This script generates the cloud structure needed.
    Flags:
      -e  Specify the env [production, staging]
      -p  Specify the project name
			-g  Specify the creator of the resource [default git username]
      -a  Specify the aws profile to use
			-r  Specify the aws default region"
		exit
		;;
	e)
		env="$OPTARG"
		;;
	p)
		project="$OPTARG"
		;;
	g)
		git_username="$OPTARG"
		;;
	a)
		AWS_PROFILE="$OPTARG"
		;;
	r)
		AWS_DEFAULT_REGION="$OPTARG"
		;;
	\?)
		echo "Invalid option: -$OPTARG"
		;;
	esac
done

if [ "$env" = "" ]; then
	echo "No env specified, use -e to select the environment"
	exit 2
fi

if [ "$project" = "" ]; then
	echo "Specify the project name with the -p flag"
	exit 2
fi

# SET AWS REGION, PROFILE AND THE WAY THE RESPONSES ARE SHOWN FOR ALL COMMANDS
export AWS_PROFILE=$AWS_PROFILE
export AWS_DEFAULT_REGION=$AWS_DEFAULT_REGION
export AWS_PAGER=""

echo "AWS_PROFILE: ${AWS_PROFILE}"
echo "AWS_DEFAULT_REGION: ${AWS_DEFAULT_REGION}"

# SET USEFULL VAR
root_folder=$(dirname $(pwd))
git_username=$(echo $(git config user.name) | tr '[:upper:]' '[:lower:]')

# SET URI FOR STACK NAME
if [ $env = "dev" ]; then
	URI="${project}"-"${env}"-"${git_username}"
else
	URI="${project}"-"${env}"
fi
